# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import executor_pb2 as executor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorStub(object):
    """Executor service for running RL agent matches
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunMatch = channel.unary_unary(
                '/executor.Executor/RunMatch',
                request_serializer=executor__pb2.MatchRequest.SerializeToString,
                response_deserializer=executor__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.ValidateAgent = channel.unary_unary(
                '/executor.Executor/ValidateAgent',
                request_serializer=executor__pb2.ValidationRequest.SerializeToString,
                response_deserializer=executor__pb2.ValidationResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/executor.Executor/HealthCheck',
                request_serializer=executor__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=executor__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ExecutorServicer(object):
    """Executor service for running RL agent matches
    """

    def RunMatch(self, request, context):
        """Run a match between agents in the specified environment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAgent(self, request, context):
        """Validate agent code before execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Get executor health status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMatch,
                    request_deserializer=executor__pb2.MatchRequest.FromString,
                    response_serializer=executor__pb2.MatchResponse.SerializeToString,
            ),
            'ValidateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAgent,
                    request_deserializer=executor__pb2.ValidationRequest.FromString,
                    response_serializer=executor__pb2.ValidationResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=executor__pb2.HealthCheckRequest.FromString,
                    response_serializer=executor__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.Executor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Executor service for running RL agent matches
    """

    @staticmethod
    def RunMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.Executor/RunMatch',
            executor__pb2.MatchRequest.SerializeToString,
            executor__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.Executor/ValidateAgent',
            executor__pb2.ValidationRequest.SerializeToString,
            executor__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.Executor/HealthCheck',
            executor__pb2.HealthCheckRequest.SerializeToString,
            executor__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
